#!/usr/bin/env python3
import os
path = "/usr/local/lib/carbunlibs"

libs = {
    "ioutils.l":"""
var internal

sub print_uint val
    echo int val
end sub

sub print_uint_w0 val
    if val != 0
        echo int val
    end if
    if val == 0
        echo bytes "0"
    end if
end sub

sub read_bytes_trim pointer val
    listen bytes internal
    trim internal val
    asm mov rax, [internal_v]
    asm mov rbx, [pa]
    asm mov qword [rbx], rax
end sub

sub print_int_array pointer num_items
    setint tempv0 0
    setint tempv1 0

    while tempv0 < num_items
        asm mov rbx, [pa]
        asm mov rax, [tempv0]
        asm mov rdx, [rbx+rax*8]
        asm mov qword [tempv1], rdx
        if tempv1 != 0
            echo int tempv1
        end if
        if tempv1 == 0
            echo bytes "0"
        end if
        setop tempv2 num_items - 2
        if tempv0 <= tempv2
            echo bytes ", "
        end if
        setop tempv0 tempv0 + 1
    end while
end sub

sub print_bytes_array pointer num_items
    setint tempv0 0
    setint tempv1 0

    while tempv0 < num_items
        asm mov rbx, [pa]
        asm mov rax, [tempv0]
        asm mov rdx, [rbx+rax*8]
        asm mov qword [tempv1], rdx
        if tempv1 != 0
            echo bytes tempv1
        end if
        if tempv1 == 0
            echo bytes "empt"
        end if
        setop tempv2 num_items - 2
        if tempv0 <= tempv2
            echo bytes ", "
        end if
        setop tempv0 tempv0 + 1
    end while
end sub

sub print_byte_array pointer num_items
    setint tempv0 0
    setint tempv1 0

    while tempv0 < num_items
        asm mov rbx, [pa]
        asm mov rax, [tempv0]
        asm mov rdx, [rbx+rax]
        asm mov byte [tempv1], dl
        if tempv1 != 0
            echo bytes tempv1
        end if
        if tempv1 == 0
            echo bytes "empt"
        end if
        setop tempv2 num_items - 2
        if tempv0 <= tempv2
            echo bytes ", "
        end if
        setop tempv0 tempv0 + 1
    end while
end sub
""",
    "mathutils.l":"""
sub sqr val res
    asm mov rax, [pa]
    asm mov rbx, [pb]
    asm imul rax, rax
    asm mov qword [rbx], rax
end sub

sub cube val res
    asm mov rax, [pa]
    asm mov rbx, [pb]
    asm imul rax, rax
    asm imul rax, [pa]
    asm mov qword [rbx], rax
end sub

sub mean pointer valpointer numno
    setchar tempv0 0
    setchar tempv1 0
    while tempv0 < numno
        asm mov rbx, [tempv0]          ; use loop index, not sum
        asm mov rcx, [pb]              ; base pointer
        asm mov rax, [tempv1]          ; current sum
        asm add rax, [rcx + rbx*8]     ; qword indexing
        asm mov qword [tempv1], rax
        setop tempv0 tempv0 + 1
    end while
    setop tempv1 tempv1 / numno
    asm mov rbx, [pa]
    asm mov rax, [tempv1]
    asm mov qword [rbx], rax
end sub

sub max pointer result numno
    setchar tempv0 0
    setchar tempv2 0
    while tempv0 < numno
        asm mov rcx, [pa]
        asm mov rbx, [tempv0]
        asm mov rax, [rcx+rbx*8]
        asm mov qword [tempv1], rax
        if tempv1 > tempv2
            setvar tempv2 tempv1
        end if
        setop tempv0 tempv0 + 1
    end while
    asm mov rdi, [pb]
    asm mov rax, [tempv2]
    asm mov qword [rdi], rax
end sub

sub min pointer result numno
    setchar tempv0 0
    setchar tempv2 0
    while tempv0 < numno
        asm mov rcx, [pa]
        asm mov rbx, [tempv0]
        asm mov rax, [rcx+rbx*8]
        asm mov qword [tempv1], rax
        if tempv1 < tempv2
            setvar tempv2 tempv1
        end if
        setop tempv0 tempv0 + 1
    end while
    asm mov rdi, [pb]
    asm mov rax, [tempv2]
    asm mov qword [rdi], rax
end sub
""",
    "byteutils.l":"""
sub push_bytes pointer index byte
    asm mov rax, [pc]              ; value
    asm mov rbx, [pa]              ; base pointer
    asm mov rcx, [pb]              ; index
    asm mov [rbx + rcx*8], rax     ; store qword
end sub

sub push_byte pointer index byte
    asm mov rax, [pc]              ; value
    asm mov rbx, [pa]              ; base pointer
    asm mov rcx, [pb]              ; index
    asm mov [rbx + rcx], al     ; store qword
end sub

sub read_bytes_arr pointer index result
    asm mov rbx, [pa]
    asm mov rax, [pb]
    asm mov rdx, [rbx+rax*8]
    asm mov rcx, [pc]
    asm mov qword [rcx], rdx
end sub

sub read_byte_arr pointer index result
    asm mov rbx, [pa]
    asm mov rax, [pb]
    asm mov rdx, [rbx+rax]
    asm mov rcx, [pc]
    asm mov byte [rcx], dl
end sub

sub clean_bytes_arr pointer size
    setint tempv0 0
    
    while tempv0 < size
        push_bytes pointer tempv0 0
        setop tempv0 tempv0 + 1
    end while
end sub

sub clean_byte_arr pointer size
    setint tempv0 0
    
    while tempv0 < size
        push_byte pointer tempv0 0
        setop tempv0 tempv0 + 1
    end while
end sub
"""
}
os.makedirs("/usr/local/lib/carbunlibs", exist_ok=True)
for lib in libs.keys():
    with open(os.path.join(path, lib), 'w') as f:
        f.write(str(libs[lib]))